name: flutter_application_4
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  carousel_slider: ^4.0.0
  flutter_webview_plugin: ^0.4.0
  google_maps_flutter: ^2.7.0
  webview_flutter: ^3.0.0
  provider: ^6.1.2
  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  
  

flutter:

  uses-material-design: true

  assets:
    - assets/téléchargement.png
    - assets/bitimg.jpg
    - assets/campus.jpg
    - assets/filiere.jpg
    - assets/social.jpg
    - assets/femalee.jpg
    - assets/intership.jpg
    - assets/ac.jpg
    - assets/work.jpg
    - assets/works.jpg
    - assets/condi.jpg
    - assets/info.jpg
    - assets/bit2.jpg
    - assets/acce.jpg
    - assets/bach.jpg
    - assets/EE1.jpg
    - assets/bit.jpg
    - assets/CS.jpg
    - assets/EE.jpg
    - assets/ME.jpg
    - assets/cond.jpg
    - assets/icon/bit.jpg
    - assets/infor.jpg
    - assets/CS1.jpg
    - assets/camp.jpg
    - assets/mecan.jpg
    - assets/stage.jpg
   



    
  

